Update run_nb.yml

diff --git a/.github/workflows/run_nb.yml b/.github/workflows/run_nb.yml
--- a/.github/workflows/run_nb.yml
+++ b/.github/workflows/run_nb.yml
@@ -10,63 +10,61 @@ on:
 
 jobs:
   job1:
-    build:
-      runs-on: ubuntu-latest
-      strategy:
-        matrix:
-          python-version: ["3.10"]
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.10"]
 
-      steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v4
+      with:
+        python-version: ${{ matrix.python-version }}
 
-      - name: Display Python version
-        run: python -c "import sys; print(sys.version)"
+    - name: Display Python version
+      run: python -c "import sys; print(sys.version)"
 
-      - name: Install dependencies
-        run: pip install jupyter nbconvert
-      - run: pip install -r requirements.txt
+    - name: Install dependencies
+      run: pip install jupyter nbconvert
+    - run: pip install -r requirements.txt
 
-      - name: Find notebooks
-        id: find-notebooks
-        run: |
-          find . -name "*.ipynb" > notebooks.txt
-          cat notebooks.txt
-        shell: bash
+    - name: Find notebooks
+      id: find-notebooks
+      run: |
+        find . -name "*.ipynb" > notebooks.txt
+        cat notebooks.txt
+      shell: bash
 
-      - name: Execute notebooks
-        run: |
-          cat notebooks.txt | while read -r notebook; do
-            jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute --inplace "$notebook"
-          done
-        continue-on-error: false
-        shell: bash
-      - name: Check for errors
-        run: |
-          if grep "raise Exception(" *.ipynb; then
-            echo "Error found in notebook(s)."
-            exit 1
-          else
-            echo "No errors found in notebooks."
-          fi
-        shell: bash
+    - name: Execute notebooks
+      run: |
+        cat notebooks.txt | while read -r notebook; do
+          jupyter nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --execute --inplace "$notebook"
+        done
+      continue-on-error: false
+      shell: bash
+    - name: Check for errors
+      run: |
+        if grep "raise Exception(" *.ipynb; then
+          echo "Error found in notebook(s)."
+          exit 1
+        else
+          echo "No errors found in notebooks."
+        fi
+      shell: bash
   job2:
     needs: job1
-    build_latex:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Compile LaTeX document
-          uses: xu-cheng/latex-action@v3
-          with:
-            working_directory: tutorial_latex_deu
-            root_file: sig_sys_ex.tex
-        - name: Upload PDF file
-          uses: actions/upload-artifact@v4
-          with:
-            name: PDF
-            path: "tutorial_latex_deu/sig_sys_ex.pdf"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Compile LaTeX document
+        uses: xu-cheng/latex-action@v3
+        with:
+          working_directory: tutorial_latex_deu
+          root_file: sig_sys_ex.tex
+      - name: Upload PDF file
+        uses: actions/upload-artifact@v4
+        with:
+          name: PDF
+          path: "tutorial_latex_deu/sig_sys_ex.pdf"
